# Generated by Django 5.2.4 on 2025-07-23 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('FR', 'Frozen'), ('RL', 'Released'), ('DM', 'Demo'), ('DV', 'In Dev'), ('GJ', 'Gamejam')], default='DV', max_length=5)),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='games_game_publish_71f202_idx')],
            },
        ),
    ]
